// Verifies docs/13-third-party-libraries/11-templ.md
//
// Requires the generated page_templ.go, which is committed. Regenerate
// with `templ generate ./...` from the examples directory after editing
// page.templ.
package templdemo

import (
	"context"
	"os"
	"strings"
	"testing"
)

func TestRenderEscapesText(t *testing.T) {
	items := []Item{
		{Name: "Widget <b>", Price: 9.5, Tags: []string{"a", "b"}},
		{Name: "Gadget", Price: 100},
	}
	var sb strings.Builder
	if err := ItemList("Shop & Co", items).Render(context.Background(), &sb); err != nil {
		t.Fatal(err)
	}
	out := sb.String()

	if strings.Contains(out, "Widget <b>") {
		t.Error("raw HTML survived into the output")
	}
	for _, want := range []string{
		"&lt;b&gt;",        // text escaped
		"Shop &amp; Co",    // title escaped
		"$9.50", "$100.00", // fmt.Sprintf ran as real Go
		"2 tags", "untagged", // both branches of the if
	} {
		if !strings.Contains(out, want) {
			t.Errorf("output missing %q\n%s", want, out)
		}
	}
}

// templ.URL replaces a dangerous scheme with its own marker, the
// equivalent of html/template's ZgotmplZ.
func TestURLSanitisation(t *testing.T) {
	cases := []struct {
		in       string
		wantSafe bool
	}{
		{"/x?q=1&b=2", true},
		{"https://example.com/a", true},
		{"mailto:a@b.c", true},
		{"javascript:alert(1)", false},
		{"data:text/html,<script>1</script>", false},
	}
	const marker = "about:invalid#TemplFailedSanitizationURL"

	for _, c := range cases {
		var sb strings.Builder
		if err := LinkTo(c.in).Render(context.Background(), &sb); err != nil {
			t.Fatal(err)
		}
		got := sb.String()
		rejected := strings.Contains(got, marker)
		if c.wantSafe && rejected {
			t.Errorf("%q was rejected: %s", c.in, got)
		}
		if !c.wantSafe && !rejected {
			t.Errorf("%q was NOT rejected: %s", c.in, got)
		}
	}
}

// The generated file must be committed and current. This catches an
// edit to page.templ that was never regenerated.
func TestGeneratedFileIsPresentAndMarked(t *testing.T) {
	b, err := os.ReadFile("page_templ.go")
	if err != nil {
		t.Fatalf("page_templ.go missing — run `templ generate`: %v", err)
	}
	src := string(b)
	if !strings.HasPrefix(src, "// Code generated by templ - DO NOT EDIT.") {
		t.Error("generated file lacks the standard marker line")
	}
	// The interpolated Go expression appears verbatim, which is why the
	// compiler catches a renamed field.
	if !strings.Contains(src, "i.Name") {
		t.Error("expected the Go expression i.Name to appear verbatim in the generated code")
	}
	if !strings.Contains(src, "templ.EscapeString") {
		t.Error("expected escaping to be applied in the generated code")
	}
}
